### ISSUE TITLE
feature request (perf): reuse packing result

### ISSUE THREAD

**Issue by tyrcho** [skjolber/3d-bin-container-packing#198]
First I wanted to thank you again @skjolber for this library which we are using daily in production. I had a look recently at the performance and I'm impressed when it packs almost 100 products in less than 1ms.

We are now considering integrating it in another area of our software where we are planning complete trips for a deliverer and thus we need to check if all products for several orders fit in its truck.

The algorithm is pretty complex, but what matters here is that we insert a few packets in the container, then a few more, try something else ...
I think we could benefit a lot in terms of performance if we had a slight change in the API to start packing from a "half-filled" container.

More formally, if the method pack would have a common type between its arguments and return type, to provide a hint (or constraint) with already positioned products.

For instance:
`public LAFFResult pack(List<Box> containerProducts, Container targetContainer, LAFFResult packHint, BooleanSupplier interrupt)`

There is probably a way to do it using `LAFFAdapter` but I'm not sure how to use it.

What do you think ?

**Comment by skjolber** [comment]
I guess [this](https://github.com/skjolber/3d-bin-container-packing/blob/master/core/src/main/java/com/github/skjolber/packing/LargestAreaFitFirstPackager.java#L65) could be decoded into a working method.  

But what you want is to be able to extract the boxes in groups, in the right order? Also that stacking physically works. 

The reason it is quick is unfortunately that it is also a bit crude. Tracking corners (i.e. [real 3D stacking](https://github.com/skjolber/3d-bin-container-packing/issues/48)) instead of 'drilling down' would be better.

**Comment by tyrcho** [comment]
Thanks for the link ! Yes I think I should be able to make it work.

The solutions of LAFF are all possible, right ? it's just that it sometimes misses better solutions ?

We are not yet looking for clever solutions like how to package together products of the same order, or how to access the orders LIFO. At the moment we were only considering total weight, then total volume but it gives solutions which are not feasible on the field. We'll integrate first your packing and even if it's not super clever that's OK since we have no way yet to tell the deliverer how to pack the same way ...

**Comment by skjolber** [comment]
Yes, however some cannot be correctly stacked, i.e. will need some kind of spacer.
