### ISSUE TITLE
Stacking in 3D

### ISSUE THREAD

**Issue by skjolber** [skjolber/3d-bin-container-packing#48]
The current LAFF and brute-force packages do level-by-level 2D stacking. Basically they place a box within a free area, leaving two seperate areas for the algorithm to recursively place the next boxes. 

The criteria for finding the best orientation and/or placement of the box is what the LAFF and brute force packagers do differently - which goes directly to the core of the problem and is hard to solve.

However the stacking itself in 3D should not be that difficult (famous last words), basically doing the same as in 2D just in more dimensions. 

Links: 

* [3D bin packing](https://www.researchgate.net/publication/273121476_A_genetic_algorithm_for_the_three-dimensional_bin_packing_problem_with_heterogeneous_bins) (inspiration, perhaps not the exact algorithm). 

 * [3D bin packing](https://pdfs.semanticscholar.org/4c80/d19b98c73c40039abc385e493083f91e3bb9.pdf)
 * [Space deframentation](https://www.ijcai.org/Proceedings/11/Papers/123.pdf)
 * [Another 3D bin packing](http://www1.dem.ist.utl.pt/engopt2010/Book_and_CD/Papers_CD_Final_Version/pdf/06/01106-01.pdf)
 * [Yet another](http://scm.snu.ac.kr/publication/paper/61.pdf) Nice figures and perhaps promising.

**Comment by swetha-98** [comment]
ISSUE:
In the free space calculation the small area which is left over is not considered wile placing the further box items in placement.
In that case even though the box items that can be placed in the available space are not placed. 

Consider an example :
Container size is 40X50X40
Product size is 20X30X10 of count 3

While trying to place the boxes into the container the first two boxes are properly fitted and the placement of the third box is done in the second level even though it can be placed in the same level with the changed orientation.
This is due to the calculation of free space in accordance with the placement of the current box.
since the remaining space is calculated from the used free space, the unused spaces are not considered for the upcoming placements.
can you help me in calculating the completely available free spaces after the placement of each boxes?

**Comment by skjolber** [comment]
@swetha-98 please provide a (failing) unit test as a pull request?

**Comment by swetha-98** [comment]
@skjolber 
the Existing junit testcases are passed.
When I tried with this example:
Container size is 40X50X60
Product size is 20X30X10 of count 3

[[Placement [0x0x0, width=20, depth=30, height=10], 
  Placement [20x0x0, width=20, depth=30, height=10]],
  [[Placement [0x0x10, width=30, depth=20, height=10]]]
	
The first two boxes are fitted in the first level and the placement of the third box is on the second level with the changed orientation, but it can be placed in the same(first) level.
This is due to the calculation of free space in accordance with the placement of the current box.
since the remaining space is calculated from the used free space, the unused spaces are not considered for the upcoming placements.
In this case,only the right(D) side free space is considered and the top space(C) is left for further placement calculations.
   ........................     ........................       ..................
 .                     .   .                  .      .              .
 .          C         .   .         C       .     .               .
 .                     .   .                  .      .               .
 ........                .   .........................      .               .
 .     .       D      .                            .        D     .
 .     .                .                           .                .
 .     .                .                           .                .
 .     .                .                           .                .
 ..............................                           ......................

When the third box is tried to placed the remaining space is only the remaining space in D is considered and not the one in C.

**Comment by skjolber** [comment]
@swetha-98 **please write a new unit test**, that fails, highlighting the problem. Paste the code here or create a pull-request.

**Comment by swetha-98** [comment]
void testStackingRectanglesOnRectangle() {

	List<Container> containers = new ArrayList<>();
	containers.add(new Container(40,50,60, 0));
	LargestAreaFitFirstPackager packager = new LargestAreaFitFirstPackager(containers, true, true, true);

	List<BoxItem> products = new ArrayList<>();

	products.add(new BoxItem(new Box("J", 20,30,10, 0), 3));

	Container fits = packager.pack(products);
	assertNotNull(fits);
	assertEquals(fits.getLevels().size(), 1);

	print(fits);
	validate(fits);
	}
The above junit test case fails.
For the above test case the first two boxes fit in first level. The third box is not getting placed in the container even-though it has space on its side.

**Comment by skjolber** [comment]
@swetha-98 this relates to the logic in the bestVolumePlacement(..) method. Basically now there is only a search for the container filling the most volume, without regard to the utility within the potential Space[]. Another strategy would be to measure the relative 'waste' of placing the boxes; i.e. prefer boxes which minimize dx+dy,dz or something like that.

**Comment by skjolber** [comment]
See the TODOs in that method. 

So in other words the problem is that the algorithm makes 2x 20x50 spaces, each which can hold a single box.

**Comment by skjolber** [comment]
@swetha-98 I've released a new version which also takes the Space size into account when choosing the right box/space (placement), however while your unit test now passes, the algorithm is just marginally better than before. 

Basically there is in general no 'right answer' in selecting the next box/space, this is more a search through all possibilities; although the algorithm could be written as to follow multiple strategies (now it follows just a single). However I suggest opening a new issue for that.

**Comment by swetha-98** [comment]
**@skjolber**  Thankyou so much. I've executed the code and it was very effective for my usecase. It's working. I'll try for multiple strategies.

**Comment by skjolber** [comment]
To solve cases like the bouwcamp codes in the tes artifact, it is necessary to keep tabs on all the 'edges' rather than the 'divide and drill down' approach currently taken.
