### ISSUE TITLE
Efi

### ISSUE THREAD

**Issue by gargolillas** [skjolber/3d-bin-container-packing#60]
Hi! 
In this Example and rotation 2D:

                containers = new ArrayList<>();
		containers.add(new Container(128, 55, 224, 0));
		packager = new LargestAreaFitFirstPackager(containers, false, true);

		products = new ArrayList<>();

                products.add(new BoxItem(new Box("a", 40, 55, 70, 0), 4));
		products.add(new BoxItem(new Box("b", 40, 54, 75, 0), 5));

RESULT: 
Container [stackWeight=0, stackHeight=140, levels=[[Placement [0x0x0, width=40, depth=55, height=70], Placement [40x0x0, width=40, depth=55, height=70], Placement [80x0x0, width=40, depth=55, height=70]], [Placement [0x0x70, width=40, depth=55, height=70]], [Placement [0x0x140, width=40, depth=54, height=75], Placement [40x0x140, width=40, depth=54, height=75], Placement [80x0x140, width=40, depth=54, height=75]]], weight=0, width=128, depth=55, height=224, volume=1576960, name=null]

Container [stackWeight=0, stackHeight=0, levels=[[Placement [0x0x0, width=40, depth=54, height=75], Placement [40x0x0, width=40, depth=54, height=75]]], weight=0, width=128, depth=55, height=224, volume=1576960, name=null]

Why creates two containers? if all boxes can put in one.  Is a mistake? Is easy to resolve?
Thanks!

**Comment by skjolber** [comment]
The algorithm takes the box with the largest footprint (40x55) and sets the height of the level according to that box. Which is 70 (40x55x70). Thus the (40x54x75) will not fit in that level because 75 > 70 (second level). 

Basically the algorithm is not 'very smart', it is just trying out a few strategies to see whether it gets a result. All algorithms are basically searches for results.

Have  you tried LargestAreaFitFirstPackager(containers, false, false)?

**Comment by skjolber** [comment]
See https://github.com/skjolber/3d-bin-container-packing/pull/61 - it that the same code  you're running? Seems the constructor you provided is not in use in the latest version?

**Comment by gargolillas** [comment]
Ok, sorry. I've seen it's correct. Thank you for all.
