### ISSUE TITLE
Looking for more details on StackableSurfaces

### ISSUE THREAD

**Issue by abest0** [skjolber/3d-bin-container-packing#619]
Hello,

Love the library. I've searched the repo for an explanation of `StackableSurfaces` and the `withRotate2d` & `withRotate3d` builder methods. The comments [here](https://github.com/skjolber/3d-bin-container-packing/blob/420fa80058934a302af0a4234b193beb84778666/api/src/main/java/com/github/skjolber/packing/api/AbstractStackableBuilder.java) provide an intuition on how these will be applied but I still seem to be missing something. 

I know this may be a lengthy topic but could you provide a bit more direction here or tests/comments to highlight how these work together?

**Comment by skjolber** [comment]
Hello @abest0, 

the library (at least tries to) defines surfaces so that the exact orientation of the boxes can be determined. Motivations:

 - vertical structural integrity (gravity)
 - horizontal structural integrity (in the direction of travel)
 - info on the box side (i.e. id) is on a specific side of the box, when unloading the operators only see the "outer page"
 - special stacking conserns
 
Hmm seems I have to fix the spaces vs tabs formatting!

**Comment by skjolber** [comment]
@abest0 did the above make sense?
