### ISSUE TITLE
PlainPackager stacks vertically after the first layer

### ISSUE THREAD

**Issue by khorchanov** [skjolber/3d-bin-container-packing#663]
Hello,

Thanks for the project.

I'd like to know if there is any reason why the PlainPackager prefers always to stack vertically after the first layer ?

![image](https://user-images.githubusercontent.com/4134635/229293170-c3acb1df-487f-4986-b232-73e4994bdd83.png)

**Comment by skjolber** [comment]
@khorchanov good question, it really prefers the "best support", as seen [here](https://github.com/skjolber/3d-bin-container-packing/blob/master/core/src/main/java/com/github/skjolber/packing/packer/plain/PlainPackager.java#L171), but looking at your figure something seems off.

I guess one issue would be that support is not calculated across multiple boxes, for example if a full layer of equally hight boxes were placed, the resulting support for the first 2nd level box would be limited to the area of the box closest to the origin. 

The relevant information does exist in ExtremePoints3D, but it thrown away. So perhaps the most straigthforward would be to improve the packager to search for more supporting boxes in order to score the lower points better in the above example.
